networks:
  ocserv:

volumes:
  ocserv:
  ocserv-log:
  shared-ssl:


services:
  ocserv:
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: ocserv-api
    restart: unless-stopped
    privileged: true
    volumes:
      - ocserv:/etc/ocserv
      - ocserv-log:/var/log/ocserv
      - shared-ssl:/etc/ocserv/certs
    networks:
      - ocserv
    ports:
      - "8080:8080"
      - "443:433/udp"
      - "443:443/tcp"
    environment:
      host: 0.0.0.0
      ALLOW_ORIGINS:
      SECRET_KEY: SECRET_KEY
      DEBUG: ${DEBUG:-false}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 20s         # Check every 20 seconds
      retries: 5            # Retry 5 times before marking the service as unhealthy
      timeout: 20s          # Wait for 20 seconds for a response
      start_period: 20s     # Wait for 20 seconds before starting the health check

