networks:
  ocserv:

volumes:
  ocserv:
  ocserv-log:
  shared-ssl:


services:
  ocserv:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: ocserv-api
    restart: unless-stopped
    privileged: true
    volumes:
      - ocserv:/etc/ocserv
      - ocserv-log:/var/log/ocserv
      - shared-ssl:/etc/ocserv/certs
    networks:
      - ocserv
    ports:
      - "8080:8080"
      - "443:433/udp"
      - "443:443/tcp"
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      SECRET_KEY: SECRET_KEY
      ALLOW_ORIGINS: http://localhost:5173
      JWT_SECRET: JWT_SECRET1234
      DATABASES: ocserv-test.db
      DEBUG: ${DEBUG:-false}

