/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SetupRequestSetup } from '../models';
// @ts-ignore
import type { SetupResponseSetup } from '../models';
/**
 * PanelApi - axios parameter creator
 * @export
 */
export const PanelApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Setup panel with admin user and
         * @summary Setup panel with admin user
         * @param {SetupRequestSetup} request setup config data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        panelSetupPost: async (request: SetupRequestSetup, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('panelSetupPost', 'request', request)
            const localVarPath = `/panel/setup/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PanelApi - functional programming interface
 * @export
 */
export const PanelApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PanelApiAxiosParamCreator(configuration)
    return {
        /**
         * Setup panel with admin user and
         * @summary Setup panel with admin user
         * @param {SetupRequestSetup} request setup config data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async panelSetupPost(request: SetupRequestSetup, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetupResponseSetup>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.panelSetupPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PanelApi.panelSetupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PanelApi - factory interface
 * @export
 */
export const PanelApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PanelApiFp(configuration)
    return {
        /**
         * Setup panel with admin user and
         * @summary Setup panel with admin user
         * @param {PanelApiPanelSetupPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        panelSetupPost(requestParameters: PanelApiPanelSetupPostRequest, options?: RawAxiosRequestConfig): AxiosPromise<SetupResponseSetup> {
            return localVarFp.panelSetupPost(requestParameters.request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for panelSetupPost operation in PanelApi.
 * @export
 * @interface PanelApiPanelSetupPostRequest
 */
export interface PanelApiPanelSetupPostRequest {
    /**
     * setup config data
     * @type {SetupRequestSetup}
     * @memberof PanelApiPanelSetupPost
     */
    readonly request: SetupRequestSetup
}

/**
 * PanelApi - object-oriented interface
 * @export
 * @class PanelApi
 * @extends {BaseAPI}
 */
export class PanelApi extends BaseAPI {
    /**
     * Setup panel with admin user and
     * @summary Setup panel with admin user
     * @param {PanelApiPanelSetupPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PanelApi
     */
    public panelSetupPost(requestParameters: PanelApiPanelSetupPostRequest, options?: RawAxiosRequestConfig) {
        return PanelApiFp(this.configuration).panelSetupPost(requestParameters.request, options).then((request) => request(this.axios, this.basePath));
    }
}

