/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsOcservUserOrGroupConfigs
 */
export interface ModelsOcservUserOrGroupConfigs {
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'cgroup'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'deny-roaming'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'dns'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'dpd'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'explicit-ipv4'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'idle-timeout'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'ipv4-netmask'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'iroute'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'keepalive'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'max-same-clients'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'mobile-dpd'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'mobile-idle-timeout'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'mtu'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'nbns'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'net-priority'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'no-route'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'no-udp'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'restrict-user-to-ports'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'restrict-user-to-routes'?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'route'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'rx-data-per-sec'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'session-timeout'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'split-dns'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'stats-report-time'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'tunnel-all-dns'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsOcservUserOrGroupConfigs
     */
    'tx-data-per-sec'?: string;
}

