/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ModelsPermission
 */
export interface ModelsPermission {
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPermission
     */
    'oc_groups'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPermission
     */
    'oc_users'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPermission
     */
    'occtl'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPermission
     */
    'see_server_logs'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPermission
     */
    'statistic'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsPermission
     */
    'system'?: boolean;
}

