/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OcOcservUser
 */
export interface OcOcservUser {
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'deactivated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'expire_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'group'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof OcOcservUser
     */
    'is_locked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OcOcservUser
     */
    'is_online'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'password'?: string;
    /**
     * Receive in bytes
     * @type {number}
     * @memberof OcOcservUser
     */
    'rx'?: number;
    /**
     * in GiB  >> x * 1024 ** 3
     * @type {number}
     * @memberof OcOcservUser
     */
    'traffic_size'?: number;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'traffic_type'?: OcOcservUserTrafficTypeEnum;
    /**
     * Transmit in bytes
     * @type {number}
     * @memberof OcOcservUser
     */
    'tx'?: number;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'uid'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof OcOcservUser
     */
    'username'?: string;
}

export const OcOcservUserTrafficTypeEnum = {
    FREE: 'Free',
    MONTHLY_TRANSMIT: 'MonthlyTransmit',
    MONTHLY_RECEIVE: 'MonthlyReceive',
    TOTALLY_TRANSMIT: 'TotallyTransmit',
    TOTALLY_RECEIVE: 'TotallyReceive'
} as const;

export type OcOcservUserTrafficTypeEnum = typeof OcOcservUserTrafficTypeEnum[keyof typeof OcOcservUserTrafficTypeEnum];


