/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PanelConfigData
 */
export interface PanelConfigData {
    /**
     * 
     * @type {string}
     * @memberof PanelConfigData
     */
    'google_captcha_secret_key'?: string;
    /**
     * 
     * @type {string}
     * @memberof PanelConfigData
     */
    'google_captcha_site_key'?: string;
}

