/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OcOcservDefaultConfigs } from './oc-ocserv-default-configs';
// May contain unused imports in some cases
// @ts-ignore
import type { PanelSetupDataAdmin } from './panel-setup-data-admin';
// May contain unused imports in some cases
// @ts-ignore
import type { PanelSetupDataConfig } from './panel-setup-data-config';

/**
 * 
 * @export
 * @interface PanelSetupData
 */
export interface PanelSetupData {
    /**
     * 
     * @type {PanelSetupDataAdmin}
     * @memberof PanelSetupData
     */
    'admin': PanelSetupDataAdmin;
    /**
     * 
     * @type {PanelSetupDataConfig}
     * @memberof PanelSetupData
     */
    'config'?: PanelSetupDataConfig;
    /**
     * 
     * @type {OcOcservDefaultConfigs}
     * @memberof PanelSetupData
     */
    'default_ocserv_group': OcOcservDefaultConfigs;
}

