/* tslint:disable */
/* eslint-disable */
/**
 * Ocserv User management Example Api
 * This is a sample Ocserv User management Api server.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ModelsOcservUserOrGroupConfigs } from './models-ocserv-user-or-group-configs';
// May contain unused imports in some cases
// @ts-ignore
import type { SetupRequestSetupConfig } from './setup-request-setup-config';

/**
 * 
 * @export
 * @interface SetupRequestSetup
 */
export interface SetupRequestSetup {
    /**
     * 
     * @type {SetupRequestSetupConfig}
     * @memberof SetupRequestSetup
     */
    'config': SetupRequestSetupConfig;
    /**
     * 
     * @type {ModelsOcservUserOrGroupConfigs}
     * @memberof SetupRequestSetup
     */
    'default_ocserv_group': ModelsOcservUserOrGroupConfigs;
}

