// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	oc "ocserv/pkg/oc"

	mock "github.com/stretchr/testify/mock"

	request "ocserv/pkg/request"
)

// OcservUserRepositoryInterface is an autogenerated mock type for the OcservUserRepositoryInterface type
type OcservUserRepositoryInterface struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *OcservUserRepositoryInterface) CreateUser(ctx context.Context, user *oc.OcservUser) (*oc.OcservUser, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *oc.OcservUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *oc.OcservUser) (*oc.OcservUser, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *oc.OcservUser) *oc.OcservUser); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oc.OcservUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *oc.OcservUser) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: ctx, pagination
func (_m *OcservUserRepositoryInterface) GetUsers(ctx context.Context, pagination *request.Pagination) (*[]oc.OcservUser, int64, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 *[]oc.OcservUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Pagination) (*[]oc.OcservUser, int64, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Pagination) *[]oc.OcservUser); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]oc.OcservUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Pagination) int64); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *request.Pagination) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetUsersWithOnlineAttr provides a mock function with given fields: ctx, pagination
func (_m *OcservUserRepositoryInterface) GetUsersWithOnlineAttr(ctx context.Context, pagination *request.Pagination) (*[]oc.OcservUser, int64, error) {
	ret := _m.Called(ctx, pagination)

	if len(ret) == 0 {
		panic("no return value specified for GetUsersWithOnlineAttr")
	}

	var r0 *[]oc.OcservUser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.Pagination) (*[]oc.OcservUser, int64, error)); ok {
		return rf(ctx, pagination)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *request.Pagination) *[]oc.OcservUser); ok {
		r0 = rf(ctx, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]oc.OcservUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *request.Pagination) int64); ok {
		r1 = rf(ctx, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *request.Pagination) error); ok {
		r2 = rf(ctx, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewOcservUserRepositoryInterface creates a new instance of OcservUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOcservUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OcservUserRepositoryInterface {
	mock := &OcservUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
