// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/oc_users": {
            "get": {
                "description": "List of Ocserv Users",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Ocserv Users"
                ],
                "summary": "List of Ocserv Users",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to order by",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order, either ASC or DESC",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Bearer TOKEN",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ocservUser.OcservUsersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/middlewares.Unauthorized"
                        }
                    }
                }
            }
        },
        "/panel/config": {
            "get": {
                "description": "Get panel Config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Panel"
                ],
                "summary": "Get panel Config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/panel.ConfigResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update Config panel",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Panel"
                ],
                "summary": "Update Config panel",
                "parameters": [
                    {
                        "description": "update config data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/panel.ConfigData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/panel.ConfigResponse"
                        }
                    }
                }
            }
        },
        "/panel/init": {
            "get": {
                "description": "Get panel Init Config",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Panel"
                ],
                "summary": "Get panel Init Config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/panel.InitResponse"
                        }
                    }
                }
            }
        },
        "/panel/login/": {
            "post": {
                "description": "Admin and Staff users login with Google captcha(captcha site key required in get config api)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Panel"
                ],
                "summary": "Admin and Staff users login",
                "parameters": [
                    {
                        "description": "setup config data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/panel.LoginData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/panel.UserResponse"
                        }
                    }
                }
            }
        },
        "/panel/setup/": {
            "post": {
                "description": "Setup panel with admin user, captcha and ocserv default group configs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Panel"
                ],
                "summary": "Setup panel with admin user",
                "parameters": [
                    {
                        "description": "setup config data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/panel.SetupData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/panel.UserResponse"
                        }
                    }
                }
            }
        },
        "/user/password": {
            "post": {
                "description": "User Change Password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "User Change Password",
                "parameters": [
                    {
                        "description": "change user password data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangePasswordData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/profile": {
            "get": {
                "description": "Get user Profile",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Get user Profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/user/staffs": {
            "get": {
                "description": "List of Staffs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "List of Staffs",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "description": "Page number, starting from 1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Number of items per page",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Field to order by",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ASC",
                            "DESC"
                        ],
                        "type": "string",
                        "description": "Sort order, either ASC or DESC",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.StaffsResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create Admin or Staff",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create Admin or Staff",
                "parameters": [
                    {
                        "description": "user create data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.CreateStaffData"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    }
                }
            }
        },
        "/user/staffs/${id}/": {
            "delete": {
                "description": "Remove Staff by given id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Remove Staff",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/user/staffs/permissions/${id}/": {
            "put": {
                "description": "Update Staff Permission by given id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update Staff Permission",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user permission",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Permission"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/user/staffs/{id}/password": {
            "post": {
                "description": "Change Staff Password by given id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Change Staff Password",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "user new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.ChangeStaffPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    },
    "definitions": {
        "middlewares.Unauthorized": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.Permission": {
            "type": "object",
            "properties": {
                "oc_groups": {
                    "type": "boolean"
                },
                "oc_users": {
                    "type": "boolean"
                },
                "occtl": {
                    "type": "boolean"
                },
                "see_server_logs": {
                    "type": "boolean"
                },
                "statistic": {
                    "type": "boolean"
                },
                "system": {
                    "type": "boolean"
                }
            }
        },
        "models.User": {
            "type": "object",
            "required": [
                "id",
                "is_admin",
                "last_login",
                "permission",
                "uid",
                "username"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "last_login": {
                    "type": "string"
                },
                "permission": {
                    "$ref": "#/definitions/models.Permission"
                },
                "uid": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "oc.OcservDefaultConfigs": {
            "type": "object",
            "properties": {
                "cgroup": {
                    "type": "string"
                },
                "deny-roaming": {
                    "type": "boolean"
                },
                "dns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "dpd": {
                    "type": "integer"
                },
                "explicit-ipv4": {
                    "type": "string"
                },
                "idle-timeout": {
                    "type": "integer"
                },
                "ipv4-network": {
                    "type": "string"
                },
                "iroute": {
                    "type": "string"
                },
                "keepalive": {
                    "type": "integer"
                },
                "max-same-clients": {
                    "type": "integer"
                },
                "mobile-dpd": {
                    "type": "integer"
                },
                "mobile-idle-timeout": {
                    "type": "integer"
                },
                "mtu": {
                    "type": "integer"
                },
                "nbns": {
                    "type": "string"
                },
                "net-priority": {
                    "type": "integer"
                },
                "no-route": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "no-udp": {
                    "type": "boolean"
                },
                "restrict-user-to-ports": {
                    "type": "string"
                },
                "restrict-user-to-routes": {
                    "type": "boolean"
                },
                "route": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rx-data-per-sec": {
                    "type": "integer"
                },
                "session-timeout": {
                    "type": "integer"
                },
                "split-dns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stats-report-time": {
                    "type": "integer"
                },
                "tunnel-all-dns": {
                    "type": "boolean"
                },
                "tx-data-per-sec": {
                    "type": "integer"
                }
            }
        },
        "oc.OcservUser": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deactivated_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "expire_at": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "is_locked": {
                    "type": "boolean"
                },
                "is_online": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "rx": {
                    "description": "Receive in bytes",
                    "type": "integer"
                },
                "traffic_size": {
                    "description": "in GiB  \u003e\u003e x * 1024 ** 3",
                    "type": "integer"
                },
                "traffic_type": {
                    "type": "string",
                    "enum": [
                        "Free",
                        "MonthlyTransmit",
                        "MonthlyReceive",
                        "TotallyTransmit",
                        "TotallyReceive"
                    ]
                },
                "tx": {
                    "description": "Transmit in bytes",
                    "type": "integer"
                },
                "uid": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "ocservUser.OcservUsersResponse": {
            "type": "object",
            "required": [
                "meta"
            ],
            "properties": {
                "meta": {
                    "$ref": "#/definitions/request.Meta"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/oc.OcservUser"
                    }
                }
            }
        },
        "panel.ConfigData": {
            "type": "object",
            "properties": {
                "google_captcha_secret_key": {
                    "type": "string"
                },
                "google_captcha_site_key": {
                    "type": "string"
                }
            }
        },
        "panel.ConfigResponse": {
            "type": "object",
            "properties": {
                "google_captcha_secret_key": {
                    "type": "string"
                },
                "google_captcha_site_key": {
                    "type": "string"
                }
            }
        },
        "panel.InitResponse": {
            "type": "object",
            "required": [
                "setup"
            ],
            "properties": {
                "google_captcha_site_key": {
                    "type": "string"
                },
                "setup": {
                    "type": "boolean"
                }
            }
        },
        "panel.LoginData": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2,
                    "example": "doe123456"
                },
                "remember_me": {
                    "type": "boolean"
                },
                "token": {
                    "type": "string"
                },
                "username": {
                    "type": "string",
                    "maxLength": 16,
                    "minLength": 2,
                    "example": "john_doe"
                }
            }
        },
        "panel.SetupData": {
            "type": "object",
            "required": [
                "admin",
                "default_ocserv_group"
            ],
            "properties": {
                "admin": {
                    "type": "object",
                    "required": [
                        "password",
                        "username"
                    ],
                    "properties": {
                        "password": {
                            "type": "string",
                            "maxLength": 16,
                            "minLength": 2,
                            "example": "doe123456"
                        },
                        "username": {
                            "type": "string",
                            "maxLength": 16,
                            "minLength": 2,
                            "example": "john_doe"
                        }
                    }
                },
                "config": {
                    "type": "object",
                    "required": [
                        "google_captcha_secret_key",
                        "google_captcha_site_key"
                    ],
                    "properties": {
                        "google_captcha_secret_key": {
                            "type": "string"
                        },
                        "google_captcha_site_key": {
                            "type": "string"
                        }
                    }
                },
                "default_ocserv_group": {
                    "$ref": "#/definitions/oc.OcservDefaultConfigs"
                }
            }
        },
        "panel.UserResponse": {
            "type": "object",
            "required": [
                "token",
                "user"
            ],
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "request.Meta": {
            "type": "object",
            "required": [
                "page",
                "page_size"
            ],
            "properties": {
                "page": {
                    "type": "integer"
                },
                "page_size": {
                    "type": "integer"
                },
                "total_records": {
                    "type": "integer"
                }
            }
        },
        "user.ChangePasswordData": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string"
                },
                "new_password": {
                    "type": "string"
                }
            }
        },
        "user.ChangeStaffPassword": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "password": {
                    "type": "string"
                }
            }
        },
        "user.CreateStaffData": {
            "type": "object",
            "required": [
                "password",
                "permission",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "permission": {
                    "$ref": "#/definitions/models.Permission"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.StaffsResponse": {
            "type": "object",
            "required": [
                "meta"
            ],
            "properties": {
                "meta": {
                    "$ref": "#/definitions/request.Meta"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ocserv User management Example Api",
	Description:      "This is a sample Ocserv User management Api server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
