basePath: /api
definitions:
  models.Permission:
    properties:
      oc_group:
        type: boolean
      oc_user:
        type: boolean
      occtl:
        type: boolean
      see_server_log:
        type: boolean
      statistic:
        type: boolean
      system:
        type: boolean
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      is_admin:
        type: boolean
      last_login:
        type: string
      permission:
        $ref: '#/definitions/models.Permission'
      uid:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
  oc.OcservDefaultConfigs:
    properties:
      cgroup:
        type: string
      deny-roaming:
        type: boolean
      dns:
        items:
          type: string
        type: array
      dpd:
        type: integer
      explicit-ipv4:
        type: string
      idle-timeout:
        type: integer
      ipv4-network:
        type: string
      iroute:
        type: string
      keepalive:
        type: integer
      max-same-clients:
        type: integer
      mobile-dpd:
        type: integer
      mobile-idle-timeout:
        type: integer
      mtu:
        type: integer
      nbns:
        type: string
      net-priority:
        type: integer
      no-route:
        items:
          type: string
        type: array
      no-udp:
        type: boolean
      restrict-user-to-ports:
        type: string
      restrict-user-to-routes:
        type: boolean
      route:
        items:
          type: string
        type: array
      rx-data-per-sec:
        type: integer
      session-timeout:
        type: integer
      split-dns:
        items:
          type: string
        type: array
      stats-report-time:
        type: integer
      tunnel-all-dns:
        type: boolean
      tx-data-per-sec:
        type: integer
    type: object
  panel.ConfigResponse:
    properties:
      google_captcha_secret_key:
        type: string
      google_captcha_site_key:
        type: string
    type: object
  panel.InitResponse:
    properties:
      google_captcha_secret_key:
        type: string
      setup:
        type: boolean
    required:
    - setup
    type: object
  panel.Login:
    properties:
      password:
        example: doe123456
        maxLength: 16
        minLength: 2
        type: string
      remember_me:
        type: boolean
      token:
        type: string
      username:
        example: john_doe
        maxLength: 16
        minLength: 2
        type: string
    required:
    - password
    - username
    type: object
  panel.SetupData:
    properties:
      admin:
        properties:
          password:
            example: doe123456
            maxLength: 16
            minLength: 2
            type: string
          username:
            example: john_doe
            maxLength: 16
            minLength: 2
            type: string
        required:
        - password
        - username
        type: object
      config:
        properties:
          google_captcha_secret_key:
            type: string
          google_captcha_site_key:
            type: string
        required:
        - google_captcha_secret_key
        - google_captcha_site_key
        type: object
      default_ocserv_group:
        $ref: '#/definitions/oc.OcservDefaultConfigs'
    required:
    - admin
    - default_ocserv_group
    type: object
  panel.UserResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/models.User'
    required:
    - token
    - user
    type: object
info:
  contact: {}
  description: This is a sample Ocserv User management Api server.
  title: Ocserv User management Example Api
  version: "1.0"
paths:
  /panel/config:
    get:
      consumes:
      - application/json
      description: Get panel Config
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/panel.ConfigResponse'
      summary: Get panel Config
      tags:
      - Panel
  /panel/init:
    get:
      consumes:
      - application/json
      description: Get panel Init Config
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/panel.InitResponse'
      summary: Get panel Init Config
      tags:
      - Panel
  /panel/login/:
    post:
      consumes:
      - application/json
      description: Admin and Staff users login with Google captcha(captcha site key
        required in get config api)
      parameters:
      - description: setup config data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/panel.Login'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/panel.UserResponse'
      summary: Admin and Staff users login
      tags:
      - Panel
  /panel/setup/:
    post:
      consumes:
      - application/json
      description: Setup panel with admin user, captcha and ocserv default group configs
      parameters:
      - description: setup config data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/panel.SetupData'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/panel.UserResponse'
      summary: Setup panel with admin user
      tags:
      - Panel
  /user/profile:
    get:
      consumes:
      - application/json
      description: Get user Profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Get user Profile
      tags:
      - User
swagger: "2.0"
